// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUWlAE07yvrnBZ19YxFA9Pgely6psRT_c',
    appId: '1:712520385580:web:83c1064841e95525953d89',
    messagingSenderId: '712520385580',
    projectId: 'my-book-b886c',
    authDomain: 'my-book-b886c.firebaseapp.com',
    databaseURL: 'https://my-book-b886c-default-rtdb.firebaseio.com',
    storageBucket: 'my-book-b886c.appspot.com',
    measurementId: 'G-1Q71P92RF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCilZkfcewFBG2EJpUNlx-qqoY288Mo6Po',
    appId: '1:269480862515:android:b952a6a4b46d8988d3d446',
    messagingSenderId: '269480862515',
    projectId: 'project-cs445',
    storageBucket: 'project-cs445.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArzFZaajIeb4WjopNwHTPrZ08fWU7PS8Y',
    appId: '1:269480862515:ios:61418ff3d5eb08b9d3d446',
    messagingSenderId: '269480862515',
    projectId: 'project-cs445',
    storageBucket: 'project-cs445.firebasestorage.app',
    iosBundleId: 'com.example.projectcs445',
  );

}